import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def test_generated_docs_references_are_current():
    result = subprocess.run(
        [sys.executable, "tools/generate_docs_references.py", "--root", ".", "--check"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    assert "generated docs references ok: 4 pages" in result.stdout


def test_generated_reference_pages_have_source_traceability():
    reference_root = ROOT / "docs" / "content" / "docs" / "reference"
    for name in ["index.mdx", "schemas.mdx", "openspec.mdx", "modes.mdx"]:
        text = (reference_root / name).read_text(encoding="utf-8")
        assert "sourcePath:" in text
        assert "Generated by tools/generate_docs_references.py" in text
        assert "/Users/" not in text
