#!/usr/bin/env python3
"""Generate deterministic docs reference pages from repo-local sources."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

GENERATED_NOTICE = "<!-- Generated by tools/generate_docs_references.py; do not edit by hand. -->"


@dataclass(frozen=True)
class Page:
    path: Path
    text: str


def slug_from_schema(path: Path) -> str:
    name = path.name
    return name.removesuffix(".schema.json").removesuffix(".json")


def md_cell(value: object) -> str:
    text = str(value if value is not None else "")
    text = text.replace("\n", " ")
    text = re.sub(r"\s+", " ", text).strip()
    return text.replace("|", "\\|")


def frontmatter(title: str, description: str, source_path: str) -> str:
    return "\n".join(
        [
            "---",
            f"title: {title}",
            f"description: {description}",
            "section: reference",
            "source: generated",
            f"sourcePath: {source_path}",
            "owner: docs",
            "status: generated",
            "safetyLevel: read",
            "---",
            "",
        ]
    )


def extract_doc_field(text: str, label: str) -> str:
    pattern = rf"^\*\*{re.escape(label)}:\*\*\s*(.+?)\s*$"
    match = re.search(pattern, text, re.MULTILINE)
    return match.group(1).strip() if match else ""


def first_heading(text: str) -> str:
    match = re.search(r"^#\s+(.+?)\s*$", text, re.MULTILINE)
    return match.group(1).strip() if match else ""


def first_section_paragraph(text: str, section: str) -> str:
    match = re.search(
        rf"^##\s+{re.escape(section)}\s*\n+(.*?)(?:\n##\s+|\Z)", text, re.MULTILINE | re.DOTALL
    )
    if not match:
        return ""
    for raw_line in match.group(1).splitlines():
        line = raw_line.strip()
        if line and not line.startswith("```"):
            return line
    return ""


def relative_to_root(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def schema_rows(root: Path) -> list[dict[str, object]]:
    rows = []
    for path in sorted((root / "schemas").glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        rows.append(
            {
                "slug": slug_from_schema(path),
                "title": data.get("title", slug_from_schema(path)),
                "type": data.get("type", "unknown"),
                "required": len(data.get("required", []))
                if isinstance(data.get("required"), list)
                else 0,
                "source": relative_to_root(path, root),
                "status": "parsed",
            }
        )
    return rows


def spec_rows(root: Path) -> list[dict[str, object]]:
    rows = []
    spec_root = root / "openspec" / "changes" / "add-spicetify-skill" / "specs"
    for path in sorted(spec_root.glob("*/spec.md")):
        text = path.read_text(encoding="utf-8")
        rows.append(
            {
                "domain": path.parent.name,
                "requirements": len(re.findall(r"^### Requirement:", text, re.MULTILINE)),
                "scenarios": len(re.findall(r"^#### Scenario:", text, re.MULTILINE)),
                "source": relative_to_root(path, root),
                "status": "headings counted",
            }
        )
    return rows


def mode_rows(root: Path) -> list[dict[str, object]]:
    rows = []
    mode_root = root / "docs" / "planning" / "add-spicetify-skill" / "modes"
    for path in sorted(mode_root.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        rows.append(
            {
                "mode": path.stem,
                "title": first_heading(text).removeprefix("Mode: ").strip() or path.stem,
                "purpose": extract_doc_field(text, "Purpose")
                or first_section_paragraph(text, "Purpose"),
                "status": extract_doc_field(text, "Status") or "unknown",
                "source": relative_to_root(path, root),
            }
        )
    return rows


def render_index(
    root: Path,
    schemas: list[dict[str, object]],
    specs: list[dict[str, object]],
    modes: list[dict[str, object]],
) -> str:
    source_path = "tools/generate_docs_references.py"
    safety_note = (
        "These pages are generated from repo-local, reviewed sources. They contain no live "
        "Spotify, Spicetify, account, token, log, screenshot, or private local-state evidence."
    )
    return (
        frontmatter(
            "Generated References",
            "Source-traced generated references for schemas, OpenSpec specs, and mode docs.",
            source_path,
        )
        + GENERATED_NOTICE
        + "\n\n# Generated References\n\n"
        + safety_note
        + "\n\n"
        + "| Source family | Count | Validation status |\n"
        + "|---|---:|---|\n"
        + f"| Schemas | {len(schemas)} | JSON parsed |\n"
        + f"| OpenSpec spec domains | {len(specs)} | Requirement and scenario headings counted |\n"
        + f"| Mode docs | {len(modes)} | Contract docs parsed |\n\n"
        + "Reference pages: `schemas`, `openspec`, and `modes`.\n"
    )


def render_schemas(root: Path, rows: list[dict[str, object]]) -> str:
    body = [
        frontmatter(
            "Schema Reference",
            "Generated inventory of root JSON schemas and validation status.",
            "schemas",
        ),
        GENERATED_NOTICE,
        "",
        "# Schema Reference",
        "",
        "| Schema | Title | Type | Required fields | Source | Status |",
        "|---|---|---|---:|---|---|",
    ]
    for row in rows:
        schema_cell = (
            f"| `{md_cell(row['slug'])}` | {md_cell(row['title'])} | "
            f"`{md_cell(row['type'])}` | {row['required']} | "
            f"`{md_cell(row['source'])}` | {md_cell(row['status'])} |"
        )
        body.append(schema_cell)
    body.append("")
    return "\n".join(body)


def render_specs(root: Path, rows: list[dict[str, object]]) -> str:
    body = [
        frontmatter(
            "OpenSpec Requirements Reference",
            "Generated inventory of OpenSpec requirement and scenario counts.",
            "openspec/changes/add-spicetify-skill/specs",
        ),
        GENERATED_NOTICE,
        "",
        "# OpenSpec Requirements Reference",
        "",
        "| Domain | Requirements | Scenarios | Source | Status |",
        "|---|---:|---:|---|---|",
    ]
    for row in rows:
        spec_cell = (
            f"| `{md_cell(row['domain'])}` | {row['requirements']} | {row['scenarios']} | "
            f"`{md_cell(row['source'])}` | {md_cell(row['status'])} |"
        )
        body.append(spec_cell)
    body.append("")
    return "\n".join(body)


def render_modes(root: Path, rows: list[dict[str, object]]) -> str:
    body = [
        frontmatter(
            "Mode Contract Reference",
            "Generated inventory of /spicetify mode contracts and source paths.",
            "docs/planning/add-spicetify-skill/modes",
        ),
        GENERATED_NOTICE,
        "",
        "# Mode Contract Reference",
        "",
        "| Mode | Purpose | Source | Status |",
        "|---|---|---|---|",
    ]
    for row in rows:
        mode_cell = (
            f"| `{md_cell(row['mode'])}` | {md_cell(row['purpose'])} | "
            f"`{md_cell(row['source'])}` | {md_cell(row['status'])} |"
        )
        body.append(mode_cell)
    body.append("")
    return "\n".join(body)


def build_pages(root: Path) -> list[Page]:
    schemas = schema_rows(root)
    specs = spec_rows(root)
    modes = mode_rows(root)
    out = root / "apps" / "docs" / "content" / "docs" / "reference"
    return [
        Page(out / "index.mdx", render_index(root, schemas, specs, modes)),
        Page(out / "schemas.mdx", render_schemas(root, schemas)),
        Page(out / "openspec.mdx", render_specs(root, specs)),
        Page(out / "modes.mdx", render_modes(root, modes)),
    ]


def write_pages(pages: list[Page]) -> list[Path]:
    changed = []
    for page in pages:
        page.path.parent.mkdir(parents=True, exist_ok=True)
        current = page.path.read_text(encoding="utf-8") if page.path.exists() else None
        if current != page.text:
            page.path.write_text(page.text, encoding="utf-8")
            changed.append(page.path)
    return changed


def check_pages(pages: list[Page]) -> list[Path]:
    drift = []
    for page in pages:
        if not page.path.exists() or page.path.read_text(encoding="utf-8") != page.text:
            drift.append(page.path)
    return drift


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument(
        "--check", action="store_true", help="fail if generated pages are missing or stale"
    )
    args = parser.parse_args(argv)

    root = args.root.resolve()
    pages = build_pages(root)
    if args.check:
        drift = check_pages(pages)
        if drift:
            for path in drift:
                print(
                    f"stale generated docs reference: {relative_to_root(path, root)}",
                    file=sys.stderr,
                )
            return 1
        print(f"generated docs references ok: {len(pages)} pages")
        return 0

    changed = write_pages(pages)
    print(f"generated docs references: {len(pages)} pages, {len(changed)} changed")
    for path in changed:
        print(relative_to_root(path, root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
